#!/bin/sh
# M18.6: Dependency audit tool test harness.
# Tests: tiq audit integrity verification, tamper detection, error cases.
set -e

export TMPDIR=/tmp
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

TIQ="${TIQ:-./build/tiq}"
if [ "${TIQ#/}" = "$TIQ" ]; then
  TIQ="$(pwd)/$TIQ"
fi

TMP_DIR=$(mktemp -d /tmp/tiq-audit-test.XXXXXX)
trap 'rm -rf "$TMP_DIR"' EXIT

fail=0

# Build audit tool
AUDIT="$ROOT/build/tiq-audit"
if ! "$TIQ" build src/tiq/tools/audit.tiq -o "$AUDIT" 2>"$TMP_DIR/build_audit.err"; then
  echo "audit_tool: FAIL (cannot build src/tiq/tools/audit.tiq)" >&2
  cat "$TMP_DIR/build_audit.err" >&2
  exit 1
fi

# Build install tool for setup
INSTALL="$ROOT/build/tiq-install"
if ! "$TIQ" build src/tiq/tools/install.tiq -o "$INSTALL" 2>"$TMP_DIR/build_install.err"; then
  echo "audit_tool: FAIL (cannot build src/tiq/tools/install.tiq)" >&2
  cat "$TMP_DIR/build_install.err" >&2
  exit 1
fi

# 1. Audit with no manifest
echo "=== 1. No manifest ==="
mkdir -p "$TMP_DIR/empty"
cd "$TMP_DIR/empty"
set +e
result=$("$AUDIT" 2>&1)
rc=$?
set -e
if [ $rc -ne 2 ]; then
  echo "audit_tool: FAIL no manifest should exit 2 (got rc=$rc)" >&2
  fail=1
fi

# 2. Audit with no lockfile
echo "=== 2. No lockfile ==="
mkdir -p "$TMP_DIR/nolock"
cd "$TMP_DIR/nolock"
cat > tiq.toml << 'EOF'
[package]
name = "nolock"
version = "0.1.0"

[tests]
dir = "tests"
EOF
set +e
result=$("$AUDIT" 2>&1)
rc=$?
set -e
if [ $rc -ne 1 ]; then
  echo "audit_tool: FAIL no lockfile should exit 1 (got rc=$rc)" >&2
  fail=1
fi
case "$result" in
  *"tiq.lock not found"*) ;;
  *) echo "audit_tool: FAIL no lockfile msg (got: $result)" >&2; fail=1 ;;
esac

# 3. Audit clean (single dep)
echo "=== 3. Audit clean ==="
mkdir -p "$TMP_DIR/lib1"
echo 'print("lib1")' > "$TMP_DIR/lib1/lib.tiq"
mkdir -p "$TMP_DIR/app1"
cd "$TMP_DIR/app1"
cat > tiq.toml << 'EOF'
[package]
name = "app1"
version = "0.1.0"

[deps]
lib1 = "path:../lib1"

[tests]
dir = "tests"
EOF
"$INSTALL" > /dev/null 2>&1
result=$("$AUDIT" 2>&1)
if [ $? -ne 0 ]; then
  echo "audit_tool: FAIL clean audit (got: $result)" >&2
  fail=1
fi
case "$result" in
  *"ok"*"1 dependencies verified"*) ;;
  *) echo "audit_tool: FAIL clean msg (got: $result)" >&2; fail=1 ;;
esac

# 4. Audit detects tampered dep
echo "=== 4. Tamper detection ==="
cd "$TMP_DIR/app1"
echo 'print("tampered")' > .tiq-deps/lib1/lib.tiq
set +e
result=$("$AUDIT" 2>&1)
rc=$?
set -e
if [ $rc -ne 1 ]; then
  echo "audit_tool: FAIL tamper should exit 1 (got rc=$rc)" >&2
  fail=1
fi
case "$result" in
  *"hash mismatch"*) ;;
  *) echo "audit_tool: FAIL tamper msg (got: $result)" >&2; fail=1 ;;
esac

# 5. Audit with multiple deps
echo "=== 5. Multi-dep audit ==="
mkdir -p "$TMP_DIR/libA" "$TMP_DIR/libB"
echo 'print("A")' > "$TMP_DIR/libA/a.tiq"
echo 'print("B")' > "$TMP_DIR/libB/b.tiq"
mkdir -p "$TMP_DIR/app2"
cd "$TMP_DIR/app2"
cat > tiq.toml << 'EOF'
[package]
name = "app2"
version = "0.1.0"

[deps]
libA = "path:../libA"
libB = "path:../libB"

[tests]
dir = "tests"
EOF
"$INSTALL" > /dev/null 2>&1
result=$("$AUDIT" 2>&1)
if [ $? -ne 0 ]; then
  echo "audit_tool: FAIL multi-dep audit (got: $result)" >&2
  fail=1
fi
case "$result" in
  *"ok"*"2 dependencies verified"*) ;;
  *) echo "audit_tool: FAIL multi-dep msg (got: $result)" >&2; fail=1 ;;
esac

# 6. Audit detects missing installed dep
echo "=== 6. Missing installed dep ==="
cd "$TMP_DIR/app2"
rm -rf .tiq-deps/libA
set +e
result=$("$AUDIT" 2>&1)
rc=$?
set -e
if [ $rc -ne 1 ]; then
  echo "audit_tool: FAIL missing dep should exit 1 (got rc=$rc)" >&2
  fail=1
fi
case "$result" in
  *"not installed"*) ;;
  *) echo "audit_tool: FAIL missing dep msg (got: $result)" >&2; fail=1 ;;
esac

# 7. Audit with no deps
echo "=== 7. No deps ==="
mkdir -p "$TMP_DIR/nodeps"
cd "$TMP_DIR/nodeps"
cat > tiq.toml << 'EOF'
[package]
name = "nodeps"
version = "0.1.0"

[tests]
dir = "tests"
EOF
# Create an empty lockfile
cat > tiq.lock << 'EOF'
# This file is automatically generated by tiq install.
# Do not edit manually.
name = "nodeps"
EOF
result=$("$AUDIT" 2>&1)
if [ $? -ne 0 ]; then
  echo "audit_tool: FAIL no deps audit (got: $result)" >&2
  fail=1
fi
case "$result" in
  *"ok"*"0 dependencies verified"*) ;;
  *) echo "audit_tool: FAIL no deps msg (got: $result)" >&2; fail=1 ;;
esac

if [ "$fail" -ne 0 ]; then
  echo "audit_tool: FAIL" >&2
  exit 1
fi

echo "audit_tool: ok (integrity verification, tamper detection, error cases)"
