#ifndef TIQ_RUNTIME_PRELUDE_H
#define TIQ_RUNTIME_PRELUDE_H

// C runtime prelude emitted verbatim at the top of every compiled program
// (plan 2.2). Kept as one concatenated literal so the emitter writes it with
// a single fputs. All helpers return int64_t (plan 1.3); keep it that way.
static const char TIQ_RUNTIME_PRELUDE[] =
    "#include <stdio.h>\n"
    "#include <stdlib.h>\n"
    "#include <string.h>\n"
    "#include <stdint.h>\n"
    "#include <sys/stat.h>\n"
    "typedef struct { const void *ptr; int len; } TiqSlice;\n"
    "typedef struct { int64_t value; int has_value; } TiqOption;\n"
    "typedef struct { int64_t value; int64_t error; int is_ok; } TiqResult;\n\n"

    "static const char *tiq_fs_read(const char *path) {\n"
    "    FILE *f = fopen(path, \"rb\");\n"
    "    if (!f) return \"\";\n"
    "    fseek(f, 0, SEEK_END);\n"
    "    long len = ftell(f);\n"
    "    fseek(f, 0, SEEK_SET);\n"
    "    if (len < 0) { fclose(f); return \"\"; }\n"
    "    char *buf = (char *)malloc(len + 1);\n"
    "    if (!buf) { fclose(f); return \"\"; }\n"
    "    size_t r = fread(buf, 1, len, f);\n"
    "    fclose(f);\n"
    "    buf[r] = '\\0';\n"
    "    return buf;\n"
    "}\n\n"

    "static int64_t tiq_fs_write(const char *path, const char *data) {\n"
    "    FILE *f = fopen(path, \"wb\");\n"
    "    if (!f) return -1;\n"
    "    size_t len = strlen(data);\n"
    "    size_t w = fwrite(data, 1, len, f);\n"
    "    fclose(f);\n"
    "    return w == len ? 0 : -1;\n"
    "}\n\n"

    "static int64_t tiq_fs_exists(const char *path) {\n"
    "    struct stat st;\n"
    "    return stat(path, &st) == 0 ? 1 : 0;\n"
    "}\n\n"

    "static int64_t tiq_proc_exec(const char *cmd) {\n"
    "    return (int64_t)system(cmd);\n"
    "}\n\n"

    "static int64_t tiq_proc_exit(int64_t code) {\n"
    "    exit((int)code);\n"
    "    return 0;\n"
    "}\n\n"

    "static int64_t tiq_json_parse_int(const char *str) {\n"
    "    if (!str) return 0;\n"
    "    return strtoll(str, NULL, 10);\n"
    "}\n\n"

    "static const char *tiq_json_encode_str(const char *str) {\n"
    "    if (!str) return \"\\\"\\\"\";\n"
    "    size_t len = strlen(str);\n"
    "    char *buf = (char *)malloc(len * 2 + 3);\n"
    "    if (!buf) return \"\\\"\\\"\";\n"
    "    size_t pos = 0;\n"
    "    buf[pos++] = '\"';\n"
    "    for (size_t i = 0; i < len; i++) {\n"
    "        if (str[i] == '\"') { buf[pos++] = '\\\\'; buf[pos++] = '\"'; }\n"
    "        else if (str[i] == '\\\\') { buf[pos++] = '\\\\'; buf[pos++] = '\\\\'; }\n"
    "        else if (str[i] == '\\n') { buf[pos++] = '\\\\'; buf[pos++] = 'n'; }\n"
    "        else buf[pos++] = str[i];\n"
    "    }\n"
    "    buf[pos++] = '\"';\n"
    "    buf[pos] = '\\0';\n"
    "    return buf;\n"
    "}\n\n"

    "static const char *tiq_net_fetch(const char *url) {\n"
    "    (void)url;\n"
    "    return \"{\\\"status\\\": 200, \\\"ok\\\": true}\";\n"
    "}\n\n"

    "static int64_t tiq_argc = 0;\n"
    "static char **tiq_argv = 0;\n\n"

    "static int64_t tiq_cli_arg_count(void) {\n"
    "    return tiq_argc > 0 ? tiq_argc - 1 : 0;\n"
    "}\n\n"

    "static const char *tiq_cli_arg(int64_t i) {\n"
    "    if (i < 0 || i + 1 >= tiq_argc) return \"\";\n"
    "    return tiq_argv[i + 1];\n"
    "}\n\n";

// Second prelude chunk: a single string literal must stay under the ISO C
// 4095-character minimum limit (-Woverlength-strings), so the emitter writes
// TIQ_RUNTIME_PRELUDE followed by TIQ_RUNTIME_PRELUDE2.
static const char TIQ_RUNTIME_PRELUDE2[] =
    // M10.2: json_get(json, key) -- single-pass JSON object member lookup
    // (LANGUAGE_SPEC §19). Missing key / non-object / malformed input all
    // yield ""; never a runtime error.
    "static const char *tiq_json_ws(const char *p) {\n"
    "    while (*p == ' ' || *p == '\\t' || *p == '\\n' || *p == '\\r') p++;\n"
    "    return p;\n"
    "}\n\n"

    "static const char *tiq_json_str_end(const char *p) {\n"
    "    if (*p != '\"') return 0;\n"
    "    p++;\n"
    "    while (*p && *p != '\"') {\n"
    "        if (*p == '\\\\' && p[1]) p++;\n"
    "        p++;\n"
    "    }\n"
    "    return *p == '\"' ? p + 1 : 0;\n"
    "}\n\n"

    "static const char *tiq_json_value_end(const char *p) {\n"
    "    if (*p == '\"') return tiq_json_str_end(p);\n"
    "    if (*p == '{' || *p == '[') {\n"
    "        int depth = 0;\n"
    "        while (*p) {\n"
    "            if (*p == '\"') { p = tiq_json_str_end(p); if (!p) return 0; continue; }\n"
    "            if (*p == '{' || *p == '[') depth++;\n"
    "            else if (*p == '}' || *p == ']') { depth--; if (depth == 0) return p + 1; }\n"
    "            p++;\n"
    "        }\n"
    "        return 0;\n"
    "    }\n"
    "    const char *s = p;\n"
    "    while (*p && *p != ',' && *p != '}' && *p != ']' &&\n"
    "           *p != ' ' && *p != '\\t' && *p != '\\n' && *p != '\\r') p++;\n"
    "    return p == s ? 0 : p;\n"
    "}\n\n"

    "static const char *tiq_json_get(const char *json, const char *key) {\n"
    "    if (!json || !key) return \"\";\n"
    "    const char *p = tiq_json_ws(json);\n"
    "    size_t klen = strlen(key);\n"
    "    if (*p != '{') return \"\";\n"
    "    p = tiq_json_ws(p + 1);\n"
    "    while (*p && *p != '}') {\n"
    "        const char *ks = p + 1;\n"
    "        const char *ke = tiq_json_str_end(p);\n"
    "        if (!ke) return \"\";\n"
    "        p = tiq_json_ws(ke);\n"
    "        if (*p != ':') return \"\";\n"
    "        p = tiq_json_ws(p + 1);\n"
    "        const char *vs = p;\n"
    "        const char *ve = tiq_json_value_end(p);\n"
    "        if (!ve) return \"\";\n"
    "        if ((size_t)(ke - 1 - ks) == klen && memcmp(ks, key, klen) == 0) {\n"
    "            size_t n = (size_t)(ve - vs);\n"
    "            char *buf = (char *)malloc(n + 1);\n"
    "            if (!buf) return \"\";\n"
    "            if (*vs == '\"') {\n"
    "                size_t pos = 0;\n"
    "                const char *q = vs + 1;\n"
    "                while (q < ve - 1) {\n"
    "                    if (*q == '\\\\' && q + 1 < ve - 1) {\n"
    "                        q++;\n"
    "                        if (*q == 'n') buf[pos++] = '\\n';\n"
    "                        else if (*q == 't') buf[pos++] = '\\t';\n"
    "                        else if (*q == 'r') buf[pos++] = '\\r';\n"
    "                        else buf[pos++] = *q;\n"
    "                        q++;\n"
    "                    } else {\n"
    "                        buf[pos++] = *q++;\n"
    "                    }\n"
    "                }\n"
    "                buf[pos] = 0;\n"
    "            } else {\n"
    "                memcpy(buf, vs, n);\n"
    "                buf[n] = 0;\n"
    "            }\n"
    "            return buf;\n"
    "        }\n"
    "        p = tiq_json_ws(ve);\n"
    "        if (*p != ',') break;\n"
    "        p = tiq_json_ws(p + 1);\n"
    "    }\n"
    "    return \"\";\n"
    "}\n\n";

#endif
