#ifndef TIQ_RUNTIME_PRELUDE_H
#define TIQ_RUNTIME_PRELUDE_H

// C runtime prelude emitted verbatim at the top of every compiled program
// (plan 2.2). Kept as one concatenated literal so the emitter writes it with
// a single fputs. All helpers return int64_t (plan 1.3); keep it that way.
static const char TIQ_RUNTIME_PRELUDE[] =
    "#include <stdio.h>\n"
    "#include <stdlib.h>\n"
    "#include <string.h>\n"
    "#include <strings.h>\n"
    "#include <stdint.h>\n"
    "#include <sys/stat.h>\n"
    "#include <sys/socket.h>\n"
    "#include <netdb.h>\n"
    "#include <unistd.h>\n"
    "typedef struct { const void *ptr; int len; } TiqSlice;\n"
    "typedef struct { int64_t value; int has_value; } TiqOption;\n"
    "typedef struct { int64_t value; int64_t error; int is_ok; } TiqResult;\n\n"

    // M9.2: allocation helpers (LANGUAGE_SPEC §16.4). Owned-string builtins
    // always return fresh heap storage; allocation failure is a deterministic
    // runtime abort.
    "static void *tiq_alloc(size_t n) {\n"
    "    void *p = malloc(n);\n"
    "    if (!p) { fprintf(stderr, \"tiq: out of memory\\n\"); exit(1); }\n"
    "    return p;\n"
    "}\n\n"

    "static const char *tiq_str_dup(const char *s) {\n"
    "    size_t n = strlen(s);\n"
    "    char *b = (char *)tiq_alloc(n + 1);\n"
    "    memcpy(b, s, n + 1);\n"
    "    return b;\n"
    "}\n\n"

    "static const char *tiq_fs_read(const char *path) {\n"
    "    FILE *f = fopen(path, \"rb\");\n"
    "    if (!f) return tiq_str_dup(\"\");\n"
    "    fseek(f, 0, SEEK_END);\n"
    "    long len = ftell(f);\n"
    "    fseek(f, 0, SEEK_SET);\n"
    "    if (len < 0) { fclose(f); return tiq_str_dup(\"\"); }\n"
    "    char *buf = (char *)tiq_alloc(len + 1);\n"
    "    size_t r = fread(buf, 1, len, f);\n"
    "    fclose(f);\n"
    "    buf[r] = '\\0';\n"
    "    return buf;\n"
    "}\n\n"

    "static int64_t tiq_fs_write(const char *path, const char *data) {\n"
    "    FILE *f = fopen(path, \"wb\");\n"
    "    if (!f) return -1;\n"
    "    size_t len = strlen(data);\n"
    "    size_t w = fwrite(data, 1, len, f);\n"
    "    fclose(f);\n"
    "    return w == len ? 0 : -1;\n"
    "}\n\n"

    "static int64_t tiq_fs_exists(const char *path) {\n"
    "    struct stat st;\n"
    "    return stat(path, &st) == 0 ? 1 : 0;\n"
    "}\n\n"

    "static int64_t tiq_proc_exec(const char *cmd) {\n"
    "    return (int64_t)system(cmd);\n"
    "}\n\n"

    "static int64_t tiq_proc_exit(int64_t code) {\n"
    "    exit((int)code);\n"
    "    return 0;\n"
    "}\n\n"

    "static int64_t tiq_json_parse_int(const char *str) {\n"
    "    if (!str) return 0;\n"
    "    return strtoll(str, NULL, 10);\n"
    "}\n\n"

    "static const char *tiq_json_encode_str(const char *str) {\n"
    "    if (!str) return tiq_str_dup(\"\\\"\\\"\");\n"
    "    size_t len = strlen(str);\n"
    "    char *buf = (char *)tiq_alloc(len * 2 + 3);\n"
    "    size_t pos = 0;\n"
    "    buf[pos++] = '\"';\n"
    "    for (size_t i = 0; i < len; i++) {\n"
    "        if (str[i] == '\"') { buf[pos++] = '\\\\'; buf[pos++] = '\"'; }\n"
    "        else if (str[i] == '\\\\') { buf[pos++] = '\\\\'; buf[pos++] = '\\\\'; }\n"
    "        else if (str[i] == '\\n') { buf[pos++] = '\\\\'; buf[pos++] = 'n'; }\n"
    "        else buf[pos++] = str[i];\n"
    "    }\n"
    "    buf[pos++] = '\"';\n"
    "    buf[pos] = '\\0';\n"
    "    return buf;\n"
    "}\n\n"

    "static int64_t tiq_argc = 0;\n"
    "static char **tiq_argv = 0;\n\n"

    "static int64_t tiq_cli_arg_count(void) {\n"
    "    return tiq_argc > 0 ? tiq_argc - 1 : 0;\n"
    "}\n\n"

    "static const char *tiq_cli_arg(int64_t i) {\n"
    "    if (i < 0 || i + 1 >= tiq_argc) return \"\";\n"
    "    return tiq_argv[i + 1];\n"
    "}\n\n";

// Second prelude chunk: a single string literal must stay under the ISO C
// 4095-character minimum limit (-Woverlength-strings), so the emitter writes
// TIQ_RUNTIME_PRELUDE followed by TIQ_RUNTIME_PRELUDE2.
static const char TIQ_RUNTIME_PRELUDE2[] =
    // M10.2: json_get(json, key) -- single-pass JSON object member lookup
    // (LANGUAGE_SPEC §19). Missing key / non-object / malformed input all
    // yield ""; never a runtime error.
    "static const char *tiq_json_ws(const char *p) {\n"
    "    while (*p == ' ' || *p == '\\t' || *p == '\\n' || *p == '\\r') p++;\n"
    "    return p;\n"
    "}\n\n"

    "static const char *tiq_json_str_end(const char *p) {\n"
    "    if (*p != '\"') return 0;\n"
    "    p++;\n"
    "    while (*p && *p != '\"') {\n"
    "        if (*p == '\\\\' && p[1]) p++;\n"
    "        p++;\n"
    "    }\n"
    "    return *p == '\"' ? p + 1 : 0;\n"
    "}\n\n"

    "static const char *tiq_json_value_end(const char *p) {\n"
    "    if (*p == '\"') return tiq_json_str_end(p);\n"
    "    if (*p == '{' || *p == '[') {\n"
    "        int depth = 0;\n"
    "        while (*p) {\n"
    "            if (*p == '\"') { p = tiq_json_str_end(p); if (!p) return 0; continue; }\n"
    "            if (*p == '{' || *p == '[') depth++;\n"
    "            else if (*p == '}' || *p == ']') { depth--; if (depth == 0) return p + 1; }\n"
    "            p++;\n"
    "        }\n"
    "        return 0;\n"
    "    }\n"
    "    const char *s = p;\n"
    "    while (*p && *p != ',' && *p != '}' && *p != ']' &&\n"
    "           *p != ' ' && *p != '\\t' && *p != '\\n' && *p != '\\r') p++;\n"
    "    return p == s ? 0 : p;\n"
    "}\n\n"

    // Shared value extraction (M10.2/M10.3): decoded strings, verbatim
    // scalar tokens, raw balanced sub-documents.
    "static const char *tiq_json_copy_value(const char *vs, const char *ve) {\n"
    "    size_t n = (size_t)(ve - vs);\n"
    "    char *buf = (char *)tiq_alloc(n + 1);\n"
    "    if (*vs == '\"') {\n"
    "        size_t pos = 0;\n"
    "        const char *q = vs + 1;\n"
    "        while (q < ve - 1) {\n"
    "            if (*q == '\\\\' && q + 1 < ve - 1) {\n"
    "                q++;\n"
    "                if (*q == 'n') buf[pos++] = '\\n';\n"
    "                else if (*q == 't') buf[pos++] = '\\t';\n"
    "                else if (*q == 'r') buf[pos++] = '\\r';\n"
    "                else buf[pos++] = *q;\n"
    "                q++;\n"
    "            } else {\n"
    "                buf[pos++] = *q++;\n"
    "            }\n"
    "        }\n"
    "        buf[pos] = 0;\n"
    "    } else {\n"
    "        memcpy(buf, vs, n);\n"
    "        buf[n] = 0;\n"
    "    }\n"
    "    return buf;\n"
    "}\n\n"

    "static const char *tiq_json_get(const char *json, const char *key) {\n"
    "    if (!json || !key) return tiq_str_dup(\"\");\n"
    "    const char *p = tiq_json_ws(json);\n"
    "    size_t klen = strlen(key);\n"
    "    if (*p != '{') return tiq_str_dup(\"\");\n"
    "    p = tiq_json_ws(p + 1);\n"
    "    while (*p && *p != '}') {\n"
    "        const char *ks = p + 1;\n"
    "        const char *ke = tiq_json_str_end(p);\n"
    "        if (!ke) return tiq_str_dup(\"\");\n"
    "        p = tiq_json_ws(ke);\n"
    "        if (*p != ':') return tiq_str_dup(\"\");\n"
    "        p = tiq_json_ws(p + 1);\n"
    "        const char *vs = p;\n"
    "        const char *ve = tiq_json_value_end(p);\n"
    "        if (!ve) return tiq_str_dup(\"\");\n"
    "        if ((size_t)(ke - 1 - ks) == klen && memcmp(ks, key, klen) == 0)\n"
    "            return tiq_json_copy_value(vs, ve);\n"
    "        p = tiq_json_ws(ve);\n"
    "        if (*p != ',') break;\n"
    "        p = tiq_json_ws(p + 1);\n"
    "    }\n"
    "    return tiq_str_dup(\"\");\n"
    "}\n\n"

    // M10.3: JSON array builtins (LANGUAGE_SPEC §19); non-array, malformed
    // input, and out-of-range indices fail soft (0 / "").
    "static int64_t tiq_json_arr_len(const char *json) {\n"
    "    if (!json) return 0;\n"
    "    const char *p = tiq_json_ws(json);\n"
    "    if (*p != '[') return 0;\n"
    "    p = tiq_json_ws(p + 1);\n"
    "    int64_t n = 0;\n"
    "    while (*p && *p != ']') {\n"
    "        const char *ve = tiq_json_value_end(p);\n"
    "        if (!ve) return 0;\n"
    "        n++;\n"
    "        p = tiq_json_ws(ve);\n"
    "        if (*p != ',') break;\n"
    "        p = tiq_json_ws(p + 1);\n"
    "    }\n"
    "    return *p == ']' ? n : 0;\n"
    "}\n\n"

    "static const char *tiq_json_arr_get(const char *json, int64_t i) {\n"
    "    if (!json || i < 0) return tiq_str_dup(\"\");\n"
    "    const char *p = tiq_json_ws(json);\n"
    "    if (*p != '[') return tiq_str_dup(\"\");\n"
    "    p = tiq_json_ws(p + 1);\n"
    "    while (*p && *p != ']') {\n"
    "        const char *vs = p;\n"
    "        const char *ve = tiq_json_value_end(p);\n"
    "        if (!ve) return tiq_str_dup(\"\");\n"
    "        if (i == 0) return tiq_json_copy_value(vs, ve);\n"
    "        i--;\n"
    "        p = tiq_json_ws(ve);\n"
    "        if (*p != ',') break;\n"
    "        p = tiq_json_ws(p + 1);\n"
    "    }\n"
    "    return tiq_str_dup(\"\");\n"
    "}\n\n";

// Third prelude chunk, same ISO C 4095-character split rationale as above.
static const char TIQ_RUNTIME_PRELUDE3[] =
    // M10.6: json_view(json, key) -- zero-copy member lookup returning a
    // TiqSlice into the source buffer (LANGUAGE_SPEC §19.1). String values
    // yield raw bytes between quotes (no escape decoding); scalars and
    // sub-documents yield verbatim text; failure yields an empty view.
    "static TiqSlice tiq_json_view(const char *json, const char *key) {\n"
    "    TiqSlice empty = { \"\", 0 };\n"
    "    if (!json || !key) return empty;\n"
    "    const char *p = tiq_json_ws(json);\n"
    "    size_t klen = strlen(key);\n"
    "    if (*p != '{') return empty;\n"
    "    p = tiq_json_ws(p + 1);\n"
    "    while (*p && *p != '}') {\n"
    "        const char *ks = p + 1;\n"
    "        const char *ke = tiq_json_str_end(p);\n"
    "        if (!ke) return empty;\n"
    "        p = tiq_json_ws(ke);\n"
    "        if (*p != ':') return empty;\n"
    "        p = tiq_json_ws(p + 1);\n"
    "        const char *vs = p;\n"
    "        const char *ve = tiq_json_value_end(p);\n"
    "        if (!ve) return empty;\n"
    "        if ((size_t)(ke - 1 - ks) == klen && memcmp(ks, key, klen) == 0) {\n"
    "            if (*vs == '\"') { vs++; ve--; }\n"
    "            TiqSlice r;\n"
    "            r.ptr = vs;\n"
    "            r.len = (int)(ve - vs);\n"
    "            return r;\n"
    "        }\n"
    "        p = tiq_json_ws(ve);\n"
    "        if (*p != ',') break;\n"
    "        p = tiq_json_ws(p + 1);\n"
    "    }\n"
    "    return empty;\n"
    "}\n\n"

    // M10.5: HTTP/1.1 chunked transfer decoding (LANGUAGE_SPEC §19.2).
    // Header name and value are matched case-insensitively.
    "static int64_t tiq_http_is_chunked(const char *h, size_t n) {\n"
    "    for (size_t i = 0; i + 18 <= n; i++) {\n"
    "        if ((i == 0 || h[i - 1] == '\\n') &&\n"
    "            strncasecmp(h + i, \"transfer-encoding:\", 18) == 0) {\n"
    "            size_t j = i + 18;\n"
    "            while (j + 7 <= n && h[j] != '\\r' && h[j] != '\\n') {\n"
    "                if (strncasecmp(h + j, \"chunked\", 7) == 0) return 1;\n"
    "                j++;\n"
    "            }\n"
    "            return 0;\n"
    "        }\n"
    "    }\n"
    "    return 0;\n"
    "}\n\n"

    // Returns the decoded body or NULL on malformed framing; chunk-size
    // extensions and trailers are ignored.
    "static char *tiq_http_unchunk(const char *p, size_t n) {\n"
    "    char *out = (char *)tiq_alloc(n + 1);\n"
    "    size_t len = 0, i = 0;\n"
    "    for (;;) {\n"
    "        size_t sz = 0;\n"
    "        int digits = 0;\n"
    "        while (i < n) {\n"
    "            char c = p[i];\n"
    "            int v;\n"
    "            if (c >= '0' && c <= '9') v = c - '0';\n"
    "            else if (c >= 'a' && c <= 'f') v = c - 'a' + 10;\n"
    "            else if (c >= 'A' && c <= 'F') v = c - 'A' + 10;\n"
    "            else break;\n"
    "            sz = sz * 16 + (size_t)v;\n"
    "            digits++;\n"
    "            i++;\n"
    "        }\n"
    "        if (digits == 0 || digits > 8) { free(out); return 0; }\n"
    "        while (i < n && p[i] != '\\r') i++;\n"
    "        if (i + 1 >= n || p[i + 1] != '\\n') { free(out); return 0; }\n"
    "        i += 2;\n"
    "        if (sz == 0) break;\n"
    "        if (i + sz + 2 > n) { free(out); return 0; }\n"
    "        memcpy(out + len, p + i, sz);\n"
    "        len += sz;\n"
    "        i += sz;\n"
    "        if (p[i] != '\\r' || p[i + 1] != '\\n') { free(out); return 0; }\n"
    "        i += 2;\n"
    "    }\n"
    "    out[len] = 0;\n"
    "    return out;\n"
    "}\n\n";

// Fourth prelude chunk, same ISO C 4095-character split rationale as above.
static const char TIQ_RUNTIME_PRELUDE4[] =
    // M10.4/M10.5: net_fetch(url) -- blocking HTTP/1.1 GET over POSIX
    // sockets (LANGUAGE_SPEC §19.2). Only http://host[:port][/path]; every
    // failure yields "" and never a runtime error.
    "static const char *tiq_net_fetch(const char *url) {\n"
    "    if (!url || strncmp(url, \"http://\", 7) != 0) return tiq_str_dup(\"\");\n"
    "    const char *hs = url + 7;\n"
    "    const char *he = hs;\n"
    "    while (*he && *he != ':' && *he != '/') he++;\n"
    "    if (he == hs || (size_t)(he - hs) >= 256) return tiq_str_dup(\"\");\n"
    "    char host[256];\n"
    "    memcpy(host, hs, (size_t)(he - hs));\n"
    "    host[he - hs] = 0;\n"
    "    char port[8] = \"80\";\n"
    "    const char *p = he;\n"
    "    if (*p == ':') {\n"
    "        p++;\n"
    "        size_t n = 0;\n"
    "        while (*p && *p != '/' && n + 1 < sizeof port) port[n++] = *p++;\n"
    "        if (n == 0 || (*p && *p != '/')) return tiq_str_dup(\"\");\n"
    "        port[n] = 0;\n"
    "    }\n"
    "    const char *path = (*p == '/') ? p : \"/\";\n"
    "    struct addrinfo hints, *res = 0;\n"
    "    memset(&hints, 0, sizeof hints);\n"
    "    hints.ai_family = AF_UNSPEC;\n"
    "    hints.ai_socktype = SOCK_STREAM;\n"
    "    if (getaddrinfo(host, port, &hints, &res) != 0 || !res) return tiq_str_dup(\"\");\n"
    "    int fd = socket(res->ai_family, res->ai_socktype, res->ai_protocol);\n"
    "    if (fd < 0) { freeaddrinfo(res); return tiq_str_dup(\"\"); }\n"
    "    if (connect(fd, res->ai_addr, res->ai_addrlen) != 0) {\n"
    "        freeaddrinfo(res); close(fd); return tiq_str_dup(\"\");\n"
    "    }\n"
    "    freeaddrinfo(res);\n"
    "    char req[512];\n"
    "    const char *reqfmt = \"GET %s HTTP/1.1\\r\\n\"\n"
    "        \"Host: %s\\r\\nConnection: close\\r\\n\\r\\n\";\n"
    "    int rl = snprintf(req, sizeof req, reqfmt, path, host);\n"
    "    if (rl <= 0 || (size_t)rl >= sizeof req ||\n"
    "        write(fd, req, (size_t)rl) != (ssize_t)rl) { close(fd); return tiq_str_dup(\"\"); }\n"
    "    size_t cap = 4096, len = 0;\n"
    "    char *buf = (char *)tiq_alloc(cap);\n"
    "    for (;;) {\n"
    "        if (len + 1025 >= cap) {\n"
    "            cap *= 2;\n"
    "            char *nb = (char *)realloc(buf, cap);\n"
    "            if (!nb) { fprintf(stderr, \"tiq: out of memory\\n\"); exit(1); }\n"
    "            buf = nb;\n"
    "        }\n"
    "        ssize_t r = read(fd, buf + len, 1024);\n"
    "        if (r < 0) { free(buf); close(fd); return tiq_str_dup(\"\"); }\n"
    "        if (r == 0) break;\n"
    "        len += (size_t)r;\n"
    "    }\n"
    "    close(fd);\n"
    "    buf[len] = 0;\n"
    "    char *body = strstr(buf, \"\\r\\n\\r\\n\");\n"
    "    if (!body) { free(buf); return tiq_str_dup(\"\"); }\n"
    "    body += 4;\n"
    "    size_t blen = len - (size_t)(body - buf);\n"
    "    if (tiq_http_is_chunked(buf, (size_t)(body - buf))) {\n"
    "        char *dec = tiq_http_unchunk(body, blen);\n"
    "        free(buf);\n"
    "        return dec ? dec : tiq_str_dup(\"\");\n"
    "    }\n"
    "    char *out = (char *)tiq_alloc(blen + 1);\n"
    "    memcpy(out, body, blen + 1);\n"
    "    free(buf);\n"
    "    return out;\n"
    "}\n\n";

#endif
