#ifndef TIQ_RUNTIME_PRELUDE_H
#define TIQ_RUNTIME_PRELUDE_H

// C runtime prelude emitted verbatim at the top of every compiled program
// (plan 2.2). Kept as one concatenated literal so the emitter writes it with
// a single fputs. All helpers return int64_t (plan 1.3); keep it that way.
static const char TIQ_RUNTIME_PRELUDE[] =
    "#include <stdio.h>\n"
    "#include <stdlib.h>\n"
    "#include <string.h>\n"
    "#include <strings.h>\n"
    "#include <stdint.h>\n"
    "#include <sys/stat.h>\n"
    "#include <sys/socket.h>\n"
    "#include <netdb.h>\n"
    "#include <netinet/in.h>\n"
"#include <sys/event.h>\n"
    "#include <unistd.h>\n"
    "typedef struct { const void *ptr; int len; } TiqSlice;\n"
    "typedef struct { int64_t value; int has_value; } TiqOption;\n"
    "typedef struct { int64_t value; int64_t error; int is_ok; } TiqResult;\n\n"

    // M9.2: allocation helpers (LANGUAGE_SPEC §16.4). Owned-string builtins
    // always return fresh heap storage; allocation failure is a deterministic
    // runtime abort.
    "static void *tiq_alloc(size_t n) {\n"
    "    void *p = malloc(n);\n"
    "    if (!p) { fprintf(stderr, \"tiq: out of memory\\n\"); exit(1); }\n"
    "    return p;\n"
    "}\n\n"

    "static const char *tiq_str_dup(const char *s) {\n"
    "    size_t n = strlen(s);\n"
    "    char *b = (char *)tiq_alloc(n + 1);\n"
    "    memcpy(b, s, n + 1);\n"
    "    return b;\n"
    "}\n\n"

    "static const char *tiq_fs_read(const char *path) {\n"
    "    FILE *f = fopen(path, \"rb\");\n"
    "    if (!f) return tiq_str_dup(\"\");\n"
    "    fseek(f, 0, SEEK_END);\n"
    "    long len = ftell(f);\n"
    "    fseek(f, 0, SEEK_SET);\n"
    "    if (len < 0) { fclose(f); return tiq_str_dup(\"\"); }\n"
    "    char *buf = (char *)tiq_alloc(len + 1);\n"
    "    size_t r = fread(buf, 1, len, f);\n"
    "    fclose(f);\n"
    "    buf[r] = '\\0';\n"
    "    return buf;\n"
    "}\n\n"

    "static int64_t tiq_fs_write(const char *path, const char *data) {\n"
    "    FILE *f = fopen(path, \"wb\");\n"
    "    if (!f) return -1;\n"
    "    size_t len = strlen(data);\n"
    "    size_t w = fwrite(data, 1, len, f);\n"
    "    fclose(f);\n"
    "    return w == len ? 0 : -1;\n"
    "}\n\n"

    "static int64_t tiq_fs_exists(const char *path) {\n"
    "    struct stat st;\n"
    "    return stat(path, &st) == 0 ? 1 : 0;\n"
    "}\n\n"

    "static int64_t tiq_proc_exec(const char *cmd) {\n"
    "    return (int64_t)system(cmd);\n"
    "}\n\n"

    "static int64_t tiq_proc_exit(int64_t code) {\n"
    "    exit((int)code);\n"
    "    return 0;\n"
    "}\n\n"

    "static int64_t tiq_json_parse_int(const char *str) {\n"
    "    if (!str) return 0;\n"
    "    return strtoll(str, NULL, 10);\n"
    "}\n\n"

    "static const char *tiq_json_encode_str(const char *str) {\n"
    "    if (!str) return tiq_str_dup(\"\\\"\\\"\");\n"
    "    size_t len = strlen(str);\n"
    "    char *buf = (char *)tiq_alloc(len * 2 + 3);\n"
    "    size_t pos = 0;\n"
    "    buf[pos++] = '\"';\n"
    "    for (size_t i = 0; i < len; i++) {\n"
    "        if (str[i] == '\"') { buf[pos++] = '\\\\'; buf[pos++] = '\"'; }\n"
    "        else if (str[i] == '\\\\') { buf[pos++] = '\\\\'; buf[pos++] = '\\\\'; }\n"
    "        else if (str[i] == '\\n') { buf[pos++] = '\\\\'; buf[pos++] = 'n'; }\n"
    "        else buf[pos++] = str[i];\n"
    "    }\n"
    "    buf[pos++] = '\"';\n"
    "    buf[pos] = '\\0';\n"
    "    return buf;\n"
    "}\n\n"

    "static int64_t tiq_argc = 0;\n"
    "static char **tiq_argv = 0;\n\n"

    "static int64_t tiq_cli_arg_count(void) {\n"
    "    return tiq_argc > 0 ? tiq_argc - 1 : 0;\n"
    "}\n\n"

    "static const char *tiq_cli_arg(int64_t i) {\n"
    "    if (i < 0 || i + 1 >= tiq_argc) return \"\";\n"
    "    return tiq_argv[i + 1];\n"
    "}\n\n";

// Second prelude chunk: a single string literal must stay under the ISO C
// 4095-character minimum limit (-Woverlength-strings), so the emitter writes
// TIQ_RUNTIME_PRELUDE followed by TIQ_RUNTIME_PRELUDE2.
static const char TIQ_RUNTIME_PRELUDE2[] =
    // M10.2: json_get(json, key) -- single-pass JSON object member lookup
    // (LANGUAGE_SPEC §19). Missing key / non-object / malformed input all
    // yield ""; never a runtime error.
    "static const char *tiq_json_ws(const char *p) {\n"
    "    while (*p == ' ' || *p == '\\t' || *p == '\\n' || *p == '\\r') p++;\n"
    "    return p;\n"
    "}\n\n"

    "static const char *tiq_json_str_end(const char *p) {\n"
    "    if (*p != '\"') return 0;\n"
    "    p++;\n"
    "    while (*p && *p != '\"') {\n"
    "        if (*p == '\\\\' && p[1]) p++;\n"
    "        p++;\n"
    "    }\n"
    "    return *p == '\"' ? p + 1 : 0;\n"
    "}\n\n"

    "static const char *tiq_json_value_end(const char *p) {\n"
    "    if (*p == '\"') return tiq_json_str_end(p);\n"
    "    if (*p == '{' || *p == '[') {\n"
    "        int depth = 0;\n"
    "        while (*p) {\n"
    "            if (*p == '\"') { p = tiq_json_str_end(p); if (!p) return 0; continue; }\n"
    "            if (*p == '{' || *p == '[') depth++;\n"
    "            else if (*p == '}' || *p == ']') { depth--; if (depth == 0) return p + 1; }\n"
    "            p++;\n"
    "        }\n"
    "        return 0;\n"
    "    }\n"
    "    const char *s = p;\n"
    "    while (*p && *p != ',' && *p != '}' && *p != ']' &&\n"
    "           *p != ' ' && *p != '\\t' && *p != '\\n' && *p != '\\r') p++;\n"
    "    return p == s ? 0 : p;\n"
    "}\n\n"

    // Shared value extraction (M10.2/M10.3): decoded strings, verbatim
    // scalar tokens, raw balanced sub-documents.
    "static const char *tiq_json_copy_value(const char *vs, const char *ve) {\n"
    "    size_t n = (size_t)(ve - vs);\n"
    "    char *buf = (char *)tiq_alloc(n + 1);\n"
    "    if (*vs == '\"') {\n"
    "        size_t pos = 0;\n"
    "        const char *q = vs + 1;\n"
    "        while (q < ve - 1) {\n"
    "            if (*q == '\\\\' && q + 1 < ve - 1) {\n"
    "                q++;\n"
    "                if (*q == 'n') buf[pos++] = '\\n';\n"
    "                else if (*q == 't') buf[pos++] = '\\t';\n"
    "                else if (*q == 'r') buf[pos++] = '\\r';\n"
    "                else buf[pos++] = *q;\n"
    "                q++;\n"
    "            } else {\n"
    "                buf[pos++] = *q++;\n"
    "            }\n"
    "        }\n"
    "        buf[pos] = 0;\n"
    "    } else {\n"
    "        memcpy(buf, vs, n);\n"
    "        buf[n] = 0;\n"
    "    }\n"
    "    return buf;\n"
    "}\n\n"

    "static const char *tiq_json_get(const char *json, const char *key) {\n"
    "    if (!json || !key) return tiq_str_dup(\"\");\n"
    "    const char *p = tiq_json_ws(json);\n"
    "    size_t klen = strlen(key);\n"
    "    if (*p != '{') return tiq_str_dup(\"\");\n"
    "    p = tiq_json_ws(p + 1);\n"
    "    while (*p && *p != '}') {\n"
    "        const char *ks = p + 1;\n"
    "        const char *ke = tiq_json_str_end(p);\n"
    "        if (!ke) return tiq_str_dup(\"\");\n"
    "        p = tiq_json_ws(ke);\n"
    "        if (*p != ':') return tiq_str_dup(\"\");\n"
    "        p = tiq_json_ws(p + 1);\n"
    "        const char *vs = p;\n"
    "        const char *ve = tiq_json_value_end(p);\n"
    "        if (!ve) return tiq_str_dup(\"\");\n"
    "        if ((size_t)(ke - 1 - ks) == klen && memcmp(ks, key, klen) == 0)\n"
    "            return tiq_json_copy_value(vs, ve);\n"
    "        p = tiq_json_ws(ve);\n"
    "        if (*p != ',') break;\n"
    "        p = tiq_json_ws(p + 1);\n"
    "    }\n"
    "    return tiq_str_dup(\"\");\n"
    "}\n\n"

    // M10.3: JSON array builtins (LANGUAGE_SPEC §19); non-array, malformed
    // input, and out-of-range indices fail soft (0 / "").
    "static int64_t tiq_json_arr_len(const char *json) {\n"
    "    if (!json) return 0;\n"
    "    const char *p = tiq_json_ws(json);\n"
    "    if (*p != '[') return 0;\n"
    "    p = tiq_json_ws(p + 1);\n"
    "    int64_t n = 0;\n"
    "    while (*p && *p != ']') {\n"
    "        const char *ve = tiq_json_value_end(p);\n"
    "        if (!ve) return 0;\n"
    "        n++;\n"
    "        p = tiq_json_ws(ve);\n"
    "        if (*p != ',') break;\n"
    "        p = tiq_json_ws(p + 1);\n"
    "    }\n"
    "    return *p == ']' ? n : 0;\n"
    "}\n\n"

    "static const char *tiq_json_arr_get(const char *json, int64_t i) {\n"
    "    if (!json || i < 0) return tiq_str_dup(\"\");\n"
    "    const char *p = tiq_json_ws(json);\n"
    "    if (*p != '[') return tiq_str_dup(\"\");\n"
    "    p = tiq_json_ws(p + 1);\n"
    "    while (*p && *p != ']') {\n"
    "        const char *vs = p;\n"
    "        const char *ve = tiq_json_value_end(p);\n"
    "        if (!ve) return tiq_str_dup(\"\");\n"
    "        if (i == 0) return tiq_json_copy_value(vs, ve);\n"
    "        i--;\n"
    "        p = tiq_json_ws(ve);\n"
    "        if (*p != ',') break;\n"
    "        p = tiq_json_ws(p + 1);\n"
    "    }\n"
    "    return tiq_str_dup(\"\");\n"
    "}\n\n";

// Third prelude chunk, same ISO C 4095-character split rationale as above.
static const char TIQ_RUNTIME_PRELUDE3[] =
    // M10.6: json_view(json, key) -- zero-copy member lookup returning a
    // TiqSlice into the source buffer (LANGUAGE_SPEC §19.1). String values
    // yield raw bytes between quotes (no escape decoding); scalars and
    // sub-documents yield verbatim text; failure yields an empty view.
    "static TiqSlice tiq_json_view(const char *json, const char *key) {\n"
    "    TiqSlice empty = { \"\", 0 };\n"
    "    if (!json || !key) return empty;\n"
    "    const char *p = tiq_json_ws(json);\n"
    "    size_t klen = strlen(key);\n"
    "    if (*p != '{') return empty;\n"
    "    p = tiq_json_ws(p + 1);\n"
    "    while (*p && *p != '}') {\n"
    "        const char *ks = p + 1;\n"
    "        const char *ke = tiq_json_str_end(p);\n"
    "        if (!ke) return empty;\n"
    "        p = tiq_json_ws(ke);\n"
    "        if (*p != ':') return empty;\n"
    "        p = tiq_json_ws(p + 1);\n"
    "        const char *vs = p;\n"
    "        const char *ve = tiq_json_value_end(p);\n"
    "        if (!ve) return empty;\n"
    "        if ((size_t)(ke - 1 - ks) == klen && memcmp(ks, key, klen) == 0) {\n"
    "            if (*vs == '\"') { vs++; ve--; }\n"
    "            TiqSlice r;\n"
    "            r.ptr = vs;\n"
    "            r.len = (int)(ve - vs);\n"
    "            return r;\n"
    "        }\n"
    "        p = tiq_json_ws(ve);\n"
    "        if (*p != ',') break;\n"
    "        p = tiq_json_ws(p + 1);\n"
    "    }\n"
    "    return empty;\n"
    "}\n\n"

    // M10.7: json_has(json, key) -- key-existence check (LANGUAGE_SPEC §19.1).
    // Returns 1 if key is a top-level member of the JSON object, 0 otherwise.
    "static int64_t tiq_json_has(const char *json, const char *key) {\n"
    "    if (!json || !key) return 0;\n"
    "    const char *p = tiq_json_ws(json);\n"
    "    size_t klen = strlen(key);\n"
    "    if (*p != '{') return 0;\n"
    "    p = tiq_json_ws(p + 1);\n"
    "    while (*p && *p != '}') {\n"
    "        const char *ks = p + 1;\n"
    "        const char *ke = tiq_json_str_end(p);\n"
    "        if (!ke) return 0;\n"
    "        p = tiq_json_ws(ke);\n"
    "        if (*p != ':') return 0;\n"
    "        p = tiq_json_ws(p + 1);\n"
    "        const char *ve = tiq_json_value_end(p);\n"
    "        if (!ve) return 0;\n"
    "        if ((size_t)(ke - 1 - ks) == klen && memcmp(ks, key, klen) == 0)\n"
    "            return 1;\n"
    "        p = tiq_json_ws(ve);\n"
    "        if (*p != ',') break;\n"
    "        p = tiq_json_ws(p + 1);\n"
    "    }\n"
    "    return 0;\n"
    "}\n\n"

    // M10.5: HTTP/1.1 chunked transfer decoding (LANGUAGE_SPEC §19.2).
    // Header name and value are matched case-insensitively.
    "static int64_t tiq_http_is_chunked(const char *h, size_t n) {\n"
    "    for (size_t i = 0; i + 18 <= n; i++) {\n"
    "        if ((i == 0 || h[i - 1] == '\\n') &&\n"
    "            strncasecmp(h + i, \"transfer-encoding:\", 18) == 0) {\n"
    "            size_t j = i + 18;\n"
    "            while (j + 7 <= n && h[j] != '\\r' && h[j] != '\\n') {\n"
    "                if (strncasecmp(h + j, \"chunked\", 7) == 0) return 1;\n"
    "                j++;\n"
    "            }\n"
    "            return 0;\n"
    "        }\n"
    "    }\n"
    "    return 0;\n"
    "}\n\n"

    // Returns the decoded body or NULL on malformed framing; chunk-size
    // extensions and trailers are ignored.
    "static char *tiq_http_unchunk(const char *p, size_t n) {\n"
    "    char *out = (char *)tiq_alloc(n + 1);\n"
    "    size_t len = 0, i = 0;\n"
    "    for (;;) {\n"
    "        size_t sz = 0;\n"
    "        int digits = 0;\n"
    "        while (i < n) {\n"
    "            char c = p[i];\n"
    "            int v;\n"
    "            if (c >= '0' && c <= '9') v = c - '0';\n"
    "            else if (c >= 'a' && c <= 'f') v = c - 'a' + 10;\n"
    "            else if (c >= 'A' && c <= 'F') v = c - 'A' + 10;\n"
    "            else break;\n"
    "            sz = sz * 16 + (size_t)v;\n"
    "            digits++;\n"
    "            i++;\n"
    "        }\n"
    "        if (digits == 0 || digits > 8) { free(out); return 0; }\n"
    "        while (i < n && p[i] != '\\r') i++;\n"
    "        if (i + 1 >= n || p[i + 1] != '\\n') { free(out); return 0; }\n"
    "        i += 2;\n"
    "        if (sz == 0) break;\n"
    "        if (i + sz + 2 > n) { free(out); return 0; }\n"
    "        memcpy(out + len, p + i, sz);\n"
    "        len += sz;\n"
    "        i += sz;\n"
    "        if (p[i] != '\\r' || p[i + 1] != '\\n') { free(out); return 0; }\n"
    "        i += 2;\n"
    "    }\n"
    "    out[len] = 0;\n"
    "    return out;\n"
    "}\n\n";

// Fourth prelude chunk, same ISO C 4095-character split rationale as above.
static const char TIQ_RUNTIME_PRELUDE4[] =
    // M10.4/M10.5: net_fetch(url) -- blocking HTTP/1.1 GET over POSIX
    // sockets (LANGUAGE_SPEC §19.2). Only http://host[:port][/path]; every
    // failure yields "" and never a runtime error.
    "static const char *tiq_net_fetch(const char *url) {\n"
    "    if (!url || strncmp(url, \"http://\", 7) != 0) return tiq_str_dup(\"\");\n"
    "    const char *hs = url + 7;\n"
    "    const char *he = hs;\n"
    "    while (*he && *he != ':' && *he != '/') he++;\n"
    "    if (he == hs || (size_t)(he - hs) >= 256) return tiq_str_dup(\"\");\n"
    "    char host[256];\n"
    "    memcpy(host, hs, (size_t)(he - hs));\n"
    "    host[he - hs] = 0;\n"
    "    char port[8] = \"80\";\n"
    "    const char *p = he;\n"
    "    if (*p == ':') {\n"
    "        p++;\n"
    "        size_t n = 0;\n"
    "        while (*p && *p != '/' && n + 1 < sizeof port) port[n++] = *p++;\n"
    "        if (n == 0 || (*p && *p != '/')) return tiq_str_dup(\"\");\n"
    "        port[n] = 0;\n"
    "    }\n"
    "    const char *path = (*p == '/') ? p : \"/\";\n"
    "    struct addrinfo hints, *res = 0;\n"
    "    memset(&hints, 0, sizeof hints);\n"
    "    hints.ai_family = AF_UNSPEC;\n"
    "    hints.ai_socktype = SOCK_STREAM;\n"
    "    if (getaddrinfo(host, port, &hints, &res) != 0 || !res) return tiq_str_dup(\"\");\n"
    "    int fd = socket(res->ai_family, res->ai_socktype, res->ai_protocol);\n"
    "    if (fd < 0) { freeaddrinfo(res); return tiq_str_dup(\"\"); }\n"
    "    if (connect(fd, res->ai_addr, res->ai_addrlen) != 0) {\n"
    "        freeaddrinfo(res); close(fd); return tiq_str_dup(\"\");\n"
    "    }\n"
    "    freeaddrinfo(res);\n"
    "    char req[512];\n"
    "    const char *reqfmt = \"GET %s HTTP/1.1\\r\\n\"\n"
    "        \"Host: %s\\r\\nConnection: close\\r\\n\\r\\n\";\n"
    "    int rl = snprintf(req, sizeof req, reqfmt, path, host);\n"
    "    if (rl <= 0 || (size_t)rl >= sizeof req ||\n"
    "        write(fd, req, (size_t)rl) != (ssize_t)rl) { close(fd); return tiq_str_dup(\"\"); }\n"
    "    size_t cap = 4096, len = 0;\n"
    "    char *buf = (char *)tiq_alloc(cap);\n"
    "    for (;;) {\n"
    "        if (len + 1025 >= cap) {\n"
    "            cap *= 2;\n"
    "            char *nb = (char *)realloc(buf, cap);\n"
    "            if (!nb) { fprintf(stderr, \"tiq: out of memory\\n\"); exit(1); }\n"
    "            buf = nb;\n"
    "        }\n"
    "        ssize_t r = read(fd, buf + len, 1024);\n"
    "        if (r < 0) { free(buf); close(fd); return tiq_str_dup(\"\"); }\n"
    "        if (r == 0) break;\n"
    "        len += (size_t)r;\n"
    "    }\n"
    "    close(fd);\n"
    "    buf[len] = 0;\n"
    "    char *body = strstr(buf, \"\\r\\n\\r\\n\");\n"
    "    if (!body) { free(buf); return tiq_str_dup(\"\"); }\n"
    "    body += 4;\n"
    "    size_t blen = len - (size_t)(body - buf);\n"
    "    if (tiq_http_is_chunked(buf, (size_t)(body - buf))) {\n"
    "        char *dec = tiq_http_unchunk(body, blen);\n"
    "        free(buf);\n"
    "        return dec ? dec : tiq_str_dup(\"\");\n"
    "    }\n"
    "    char *out = (char *)tiq_alloc(blen + 1);\n"
    "    memcpy(out, body, blen + 1);\n"
    "    free(buf);\n"
    "    return out;\n"
    "}\n\n";

// Fifth prelude chunk: M10.8 TCP socket primitives (LANGUAGE_SPEC §19.3).
static const char TIQ_RUNTIME_PRELUDE5[] =
    "static int64_t tiq_net_listen(int64_t port) {\n"
    "    int fd = socket(AF_INET, SOCK_STREAM, 0);\n"
    "    if (fd < 0) return -1;\n"
    "    int opt = 1;\n"
    "    setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof opt);\n"
    "    struct sockaddr_in a;\n"
    "    memset(&a, 0, sizeof a);\n"
    "    a.sin_family = AF_INET;\n"
    "    a.sin_addr.s_addr = htonl(INADDR_LOOPBACK);\n"
    "    a.sin_port = htons((uint16_t)port);\n"
    "    if (bind(fd, (struct sockaddr *)&a, sizeof a) != 0 ||\n"
    "        listen(fd, 1) != 0) { close(fd); return -1; }\n"
    "    return fd;\n"
    "}\n\n"

    "static int64_t tiq_net_accept(int64_t fd) {\n"
    "    int c = accept((int)fd, 0, 0);\n"
    "    return c < 0 ? -1 : c;\n"
    "}\n\n"

    "static int64_t tiq_net_connect(int64_t port) {\n"
    "    int fd = socket(AF_INET, SOCK_STREAM, 0);\n"
    "    if (fd < 0) return -1;\n"
    "    struct sockaddr_in a;\n"
    "    memset(&a, 0, sizeof a);\n"
    "    a.sin_family = AF_INET;\n"
    "    a.sin_addr.s_addr = htonl(INADDR_LOOPBACK);\n"
    "    a.sin_port = htons((uint16_t)port);\n"
    "    if (connect(fd, (struct sockaddr *)&a, sizeof a) != 0) {\n"
    "        close(fd); return -1;\n"
    "    }\n"
    "    return fd;\n"
    "}\n\n"

    "static const char *tiq_net_recv(int64_t fd) {\n"
    "    char *buf = (char *)tiq_alloc(4097);\n"
    "    ssize_t r = read((int)fd, buf, 4096);\n"
    "    if (r <= 0) { free(buf); return tiq_str_dup(\"\"); }\n"
    "    buf[r] = 0;\n"
    "    return buf;\n"
    "}\n\n"

    "static int64_t tiq_net_send(int64_t fd, const char *data) {\n"
    "    if (!data) return -1;\n"
    "    size_t n = strlen(data);\n"
    "    ssize_t w = write((int)fd, data, n);\n"
    "    return w < 0 ? -1 : (int64_t)w;\n"
    "}\n\n"

    "static int64_t tiq_net_close(int64_t fd) {\n"
    "    return close((int)fd) == 0 ? 0 : -1;\n"
    "}\n\n"

    "static int64_t tiq_net_port(int64_t fd) {\n"
    "    struct sockaddr_in a;\n"
    "    socklen_t len = sizeof a;\n"
    "    if (getsockname((int)fd, (struct sockaddr *)&a, &len) != 0) return -1;\n"
    "    return ntohs(a.sin_port);\n"
    "}\n\n"

    "static int64_t tiq_net_shutdown(int64_t fd) {\n"
    "    return shutdown((int)fd, SHUT_WR) == 0 ? 0 : -1;\n"
    "}\n\n"

    "static const char *tiq_http_method(const char *req) {\n"
    "    if (!req || !req[0]) return tiq_str_dup(\"\");\n"
    "    const char *sp = strchr(req, ' ');\n"
    "    if (!sp) return tiq_str_dup(req);\n"
    "    size_t n = (size_t)(sp - req);\n"
    "    char *out = (char *)tiq_alloc(n + 1);\n"
    "    memcpy(out, req, n); out[n] = 0;\n"
    "    return out;\n"
    "}\n\n"

    "static const char *tiq_http_path(const char *req) {\n"
    "    if (!req) return tiq_str_dup(\"\");\n"
    "    const char *sp1 = strchr(req, ' ');\n"
    "    if (!sp1) return tiq_str_dup(\"\");\n"
    "    const char *sp2 = strchr(sp1 + 1, ' ');\n"
    "    if (!sp2) return tiq_str_dup(\"\");\n"
    "    size_t n = (size_t)(sp2 - sp1 - 1);\n"
    "    char *out = (char *)tiq_alloc(n + 1);\n"
    "    memcpy(out, sp1 + 1, n); out[n] = 0;\n"
    "    return out;\n"
    "}\n\n"

    "static struct kevent tiq_ev_out_[64];\n"
    "static int64_t tiq_ev_nout_ = 0;\n\n"

    "static int64_t tiq_ev_loop(void) {\n"
    "    static int kq = -2;\n"
    "    if (kq == -2) kq = kqueue();\n"
    "    return kq;\n"
    "}\n\n"

    "static int64_t tiq_ev_add(int64_t loop, int64_t fd) {\n"
    "    struct kevent ev;\n"
    "    EV_SET(&ev, fd, EVFILT_READ, EV_ADD, 0, 0, NULL);\n"
    "    return kevent((int)loop, &ev, 1, NULL, 0, NULL) == 0 ? 0 : -1;\n"
    "}\n\n"

    "static int64_t tiq_ev_wait(int64_t loop, int64_t timeout_ms) {\n"
    "    struct timespec ts;\n"
    "    struct timespec *tsp = NULL;\n"
    "    if (timeout_ms >= 0) {\n"
    "        ts.tv_sec = timeout_ms / 1000;\n"
    "        ts.tv_nsec = (timeout_ms % 1000) * 1000000L;\n"
    "        tsp = &ts;\n"
    "    }\n"
    "    tiq_ev_nout_ = kevent((int)loop, NULL, 0, tiq_ev_out_, 64, tsp);\n"
    "    return tiq_ev_nout_;\n"
    "}\n\n"

    "static int64_t tiq_ev_ready(int64_t loop, int64_t fd) {\n"
    "    (void)loop;\n"
    "    for (int i = 0; i < tiq_ev_nout_; i++)\n"
    "        if ((int64_t)tiq_ev_out_[i].ident == fd) return 1;\n"
    "    return 0;\n"
    "}\n\n";

// M10.11: JSON object encoder (sixth chunk, ISO C 4095-char literal split).
static const char TIQ_RUNTIME_PRELUDE6[] =
    "static const char *tiq_json_set(const char *json, const char *key, const char *val) {\n"
    "    if (!json || !key || !val) return tiq_str_dup(\"{}\");\n"
    "    size_t jl = strlen(json), kl = strlen(key), vl = strlen(val);\n"
    "    const char *p = json;\n"
    "    while (*p == ' ' || *p == '\\t' || *p == '\\n' || *p == '\\r') p++;\n"
    "    if (*p != '{') {\n"
    "        size_t n = kl + vl + 5;\n"
    "        char *r = (char *)tiq_alloc(n + 1);\n"
    "        snprintf(r, n + 1, \"{\\\"%s\\\":%s}\", key, val);\n"
    "        return r;\n"
    "    }\n"
    "    char pat[258];\n"
    "    if (kl > 254) return tiq_str_dup(json);\n"
    "    snprintf(pat, sizeof pat, \"\\\"%s\\\"\", key);\n"
    "    size_t pl = strlen(pat);\n"
    "    const char *m = NULL; int depth = 0; int in_str = 0;\n"
    "    for (const char *s = p + 1; *s; s++) {\n"
    "        if (in_str) { if (*s == '\\\\') s++; else if (*s == '\"') in_str = 0; continue; }\n"
    "        if (*s == '\"') {\n"
    "            if (depth == 0 && !m && strncmp(s, pat, pl) == 0) m = s;\n"
    "            in_str = 1; continue;\n"
    "        }\n"
    "        if (*s == '{' || *s == '[') depth++;\n"
    "        else if (*s == '}' || *s == ']') depth--;\n"
    "    }\n"
    "    if (m) {\n"
    "        const char *c = m + pl;\n"
    "        while (*c == ' ' || *c == '\\t' || *c == '\\n' || *c == '\\r') c++;\n"
    "        if (*c != ':') return tiq_str_dup(json);\n"
    "        c++;\n"
    "        while (*c == ' ' || *c == '\\t' || *c == '\\n' || *c == '\\r') c++;\n"
    "        const char *ve = c; int d2 = 0; int s2 = 0;\n"
    "        while (*ve) {\n"
    "            if (s2) { if (*ve == '\\\\') ve++; else if (*ve == '\"') s2 = 0; ve++; continue; }\n"
    "            if (*ve == '\"') { s2 = 1; ve++; continue; }\n"
    "            if (*ve == '{' || *ve == '[') { d2++; ve++; continue; }\n"
    "            if (*ve == '}' || *ve == ']') { if (d2 == 0) break; d2--; ve++; continue; }\n"
    "            if (*ve == ',' && d2 == 0) break;\n"
    "            ve++;\n"
    "        }\n"
    "        size_t n = (size_t)(c - json) + vl + strlen(ve) + 1;\n"
    "        char *r = (char *)tiq_alloc(n + 1);\n"
    "        size_t pre = (size_t)(c - json);\n"
    "        memcpy(r, json, pre);\n"
    "        memcpy(r + pre, val, vl);\n"
    "        strcpy(r + pre + vl, ve);\n"
    "        return r;\n"
    "    }\n"
    "    const char *close = NULL; int d3 = 0; int s3 = 0;\n"
    "    for (const char *s = p; *s; s++) {\n"
    "        if (s3) { if (*s == '\\\\') s++; else if (*s == '\"') s3 = 0; continue; }\n"
    "        if (*s == '\"') { s3 = 1; continue; }\n"
    "        if (*s == '{' || *s == '[') d3++;\n"
    "        else if (*s == '}' || *s == ']') { d3--; if (d3 == 0) { close = s; break; } }\n"
    "    }\n"
    "    if (!close) return tiq_str_dup(json);\n"
    "    int empty = 1;\n"
    "    for (const char *s = p + 1; s < close; s++)\n"
    "        if (*s != ' ' && *s != '\\t' && *s != '\\n' && *s != '\\r') { empty = 0; break; }\n"
    "    size_t n = jl + kl + vl + (empty ? 4 : 5);\n"
    "    char *r = (char *)tiq_alloc(n + 1);\n"
    "    size_t pre = (size_t)(close - json);\n"
    "    memcpy(r, json, pre);\n"
    "    char *w = r + pre;\n"
    "    if (!empty) *w++ = ',';\n"
    "    *w++ = '\"';\n"
    "    memcpy(w, key, kl); w += kl;\n"
    "    *w++ = '\"'; *w++ = ':';\n"
    "    memcpy(w, val, vl); w += vl;\n"
    "    strcpy(w, close);\n"
    "    return r;\n"
    "}\n\n";


// M10.12: JSON member deletion (seventh chunk, ISO C 4095-char literal split).
static const char TIQ_RUNTIME_PRELUDE7[] =
    "static const char *tiq_json_del(const char *json, const char *key) {\n"
    "    if (!json || !key) return tiq_str_dup(\"\");\n"
    "    size_t jl = strlen(json), kl = strlen(key);\n"
    "    const char *p = json;\n"
    "    while (*p == ' ' || *p == '\\t' || *p == '\\n' || *p == '\\r') p++;\n"
    "    if (*p != '{') return tiq_str_dup(json);\n"
    "    char pat[258];\n"
    "    if (kl > 254) return tiq_str_dup(json);\n"
    "    snprintf(pat, sizeof pat, \"\\\"%s\\\"\", key);\n"
    "    size_t pl = strlen(pat);\n"
    "    const char *m = NULL; int depth = 0; int in_str = 0;\n"
    "    for (const char *s = p + 1; *s; s++) {\n"
    "        if (in_str) { if (*s == '\\\\') s++; else if (*s == '\"') in_str = 0; continue; }\n"
    "        if (*s == '\"') {\n"
    "            if (depth == 0 && !m && strncmp(s, pat, pl) == 0) m = s;\n"
    "            in_str = 1; continue;\n"
    "        }\n"
    "        if (*s == '{' || *s == '[') depth++;\n"
    "        else if (*s == '}' || *s == ']') depth--;\n"
    "    }\n"
    "    if (!m) return tiq_str_dup(json);\n"
    "    const char *comma_before = NULL;\n"
    "    for (const char *s = m - 1; s > p; s--) {\n"
    "        if (*s == ' ' || *s == '\\t' || *s == '\\n' || *s == '\\r') continue;\n"
    "        if (*s == ',') comma_before = s;\n"
    "        break;\n"
    "    }\n"
    "    const char *c = m + pl;\n"
    "    while (*c == ' ' || *c == '\\t' || *c == '\\n' || *c == '\\r') c++;\n"
    "    if (*c != ':') return tiq_str_dup(json);\n"
    "    c++;\n"
    "    while (*c == ' ' || *c == '\\t' || *c == '\\n' || *c == '\\r') c++;\n"
    "    const char *ve = c; int d2 = 0; int s2 = 0;\n"
    "    while (*ve) {\n"
    "        if (s2) { if (*ve == '\\\\') ve++; else if (*ve == '\"') s2 = 0; ve++; continue; }\n"
    "        if (*ve == '\"') { s2 = 1; ve++; continue; }\n"
    "        if (*ve == '{' || *ve == '[') { d2++; ve++; continue; }\n"
    "        if (*ve == '}' || *ve == ']') { if (d2 == 0) break; d2--; ve++; continue; }\n"
    "        if (*ve == ',' && d2 == 0) break;\n"
    "        ve++;\n"
    "    }\n"
    "    const char *rm_start, *rm_end;\n"
    "    if (comma_before) {\n"
    "        rm_start = comma_before;\n"
    "        rm_end = ve;\n"
    "    } else {\n"
    "        rm_start = m;\n"
    "        rm_end = ve;\n"
    "        if (*ve == ',') rm_end = ve + 1;\n"
    "    }\n"
    "    size_t n = jl - (size_t)(rm_end - rm_start) + 1;\n"
    "    char *r = (char *)tiq_alloc(n + 1);\n"
    "    size_t pre = (size_t)(rm_start - json);\n"
    "    memcpy(r, json, pre);\n"
    "    strcpy(r + pre, rm_end);\n"
    "    return r;\n"
    "}\n";

#endif
