#!/bin/sh
# Regenerate the Tiq emitter's C runtime text from the authoritative bootstrap
# emitter. Each C source line becomes its own Tiq string, keeping every literal
# comfortably below ISO C's 4095-byte translation limit.
set -eu

TIQ_BIN="${TIQ:-./build/tiq}"
OUT="${OUT:-src/tiq/emit_c_runtime.tiq}"
TMP_DIR=$(mktemp -d "${TMPDIR:-/tmp}/tiq-runtime-gen-XXXXXX")
trap 'rm -rf "$TMP_DIR"' EXIT INT TERM
: >"$TMP_DIR/empty.tiq"
"$TIQ_BIN" emit-c "$TMP_DIR/empty.tiq" >"$TMP_DIR/empty.c"

awk '
BEGIN {
    print "// Generated by tools/gen_selfhost_runtime.sh from the bootstrap runtime."
    print "// Do not edit by hand; regenerate after changing include/runtime*.h."
    print ""
    print "ec_runtime b:strbuf -> i64 -> {"
}
/^int main\(int argc, char \*\*argv\)/ { done = 1 }
!done {
    line = $0
    sub(/^static /, "", line)
    gsub(/\\/, "\\\\", line)
    gsub(/\"/, "\\\"", line)
    print "    str_buf_append(b, \"" line "\\n\")"
}
END {
    print "    0"
    print "}"
}
' "$TMP_DIR/empty.c" >"$OUT"
